name: Update Stock Market Datas
on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: Update Stock Market Data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation - Generating GitHub contribution grid snake
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: JosePeeterson
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Build and deploy the updated data
      - name: Build and Deploy
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
